"""Static curation data for the spirectl_lib/data JSON store.

Structured overlays only — the store is programmatic (see
spirectl_lib/schema.py); prose doctrine lives in memory/lessons.
"""

# live creature display name -> monster key (codex probe aid)
# live creature display name -> monster key (codex probe aid)
CREATURE_NAME_TO_KEY = {'铁甲战士': 'IRONCLAD',
 '静默猎手': 'SILENT',
 '储君': 'REGENT',
 '亡灵契约师': 'NECROBINDER',
 '故障机器人': 'DEFECT',
 '奥斯提': 'Osty',
 '树叶史莱姆（中）': 'LeafSlimeM',
 '树叶史莱姆（小）': 'LeafSlimeS',
 '树枝史莱姆（中）': 'TwigSlimeM',
 '树枝史莱姆（小）': 'TwigSlimeS',
 '缩小甲虫': 'ShrinkerBeetle',
 '墨宝': 'Inklet',
 '蛮兽': 'Mawler',
 '小啃兽': 'Nibbit',
 '闪光贾克斯果': 'SnappingJaxfruit',
 '飞蝇菌子': 'Flyconid',
 '毛绒伏地虫': 'FuzzyWurmCrawler',
 '雾菇': 'Fogmog',
 '利齿之眼': 'EyeWithTeeth',
 '地道虫': 'Tunneler',
 '劫掠者刺客': 'AssassinRubyRaider',
 '劫掠者斧手': 'AxeRubyRaider',
 '劫掠者暴徒': 'BruteRubyRaider',
 '劫掠者弩手': 'CrossbowRubyRaider',
 '劫掠者追踪手': 'TrackerRubyRaider',
 '异蛙寄生虫': 'PhrogParasite',
 '扭动虫': 'Wriggler',
 '蛇行扼杀者': 'SlitheringStrangler',
 '藤蔓蹒跚者': 'VineShambler',
 '藤蔓妖': 'VineShambler',
 '外骨骼虫': 'Exoskeleton',
 '多尼斯异鸟': 'Byrdonis',
 '旧日雕像': 'BygoneEffigy',
 '同族神官': 'KinPriest',
 '同族信徒': 'KinFollower',
 '噬尸蛞蝓': 'CorpseSlug',
 '仪式兽': 'CeremonialBeast',
 '盛碗虫（卵）': 'BowlbugEgg',
 '盛碗虫（蜜）': 'BowlbugNectar',
 '盛碗虫（石）': 'BowlbugRock',
 '盛碗虫（丝）': 'BowlbugSilk',
 '异螨': 'Myte',
 '啃咬机': 'Chomper',
 '猎人杀手': 'HunterKiller',
 '虱虫之祖': 'LouseProgenitor',
 '直飞产卵虫': 'Ovicopter',
 '结实的卵': 'ToughEgg',
 '熟睡甲虫': 'SlumberingBeetle',
 '棘刺蟾蜍': 'SpinyToad',
 '感染棱柱': 'InfestedPrism',
 '立柱构造体': 'InfestedPrism',
 '蜂群术士': 'Entomancer',
 '残杀千足虫': 'Decimillipede',
 '胧光怪': 'TheObscura',
 '墨影幻灵': 'Parafright',
 '寄生惧魔': 'Parafright',
 '偷窃草蜢': 'ThievingHopper',
 '无厌沙虫': 'TheInsatiable',
 '碾碎爪': 'Crusher',
 '火箭': 'Rocket',
 '知识恶魔': 'KnowledgeDemon',
 '女王': 'Queen',
 '实验体 #C8': 'TestSubject',
 '实验体 #C9': 'TestSubject',
 '实验体 #C10': 'TestSubject',
 '灵魂枢纽': 'SoulNexus',
 '猫头鹰法官': 'OwlMagistrate',
 '连枷骑士': 'FlailKnight',
 '幽灵骑士': 'SpectralKnight',
 '魔法骑士': 'MagiKnight',
 '失落之物': 'LostThing',
 '遗忘之物': 'ForgottenThing',
 '火炬头聚合体': 'TorchHeadAggregate',
 '虔诚雕刻师': 'DevotedSculptor',
 '史莱姆狂战士': 'SlimedBerserker',
 '活体盾': 'LivingShield',
 '高塔炮手': 'TowerGunner',
 '青蛙骑士': 'FrogKnight',
 '电球头': 'GlobeHead',
 '机甲骑士': 'MechKnight',
 '战斗好伙伴V3.0': 'BattleFriendV3',
 '咬人卷轴': 'ScrollOfBiting',
 '拳击构装体': 'PunchConstruct',
 '永世沙漏': 'Aeonglass',
 '瀑布巨兽': 'WaterfallGiant',
 '灵魂异鱼': 'SoulFysh',
 '乐加维林族母': 'LagavulinMatriarch',
 '下水道蚌': 'SewerClam',
 '蟾蜍蝌蚪': 'Toadpole',
 '鬼祟珊瑚群': 'CoralCluster',
 '淤泥旋螺': 'SludgeSpinner',
 '花园幽灵鳗': 'PhantasmalGardener',
 '骇鳗': 'TerrorEel',
 '幽灵船': 'HauntedShip',
 '地精佣兵': 'GremlinMerc',
 '卑鄙地精': 'SneakyGremlin',
 '胖地精': 'FatGremlin',
 '钙化邪教徒': 'CalcifiedCultist',
 '潮湿邪教徒': 'DampCultist',
 '活雾': 'LivingFog',
 '气态炸弹': 'GasBomb',
 '幼虫': 'Larvae',
 '海洋混混': 'CorpseSlug',
 '组装师': 'Assembler',
 '神秘骑士': 'MysteriousKnight',
 '佩尔的士兵': 'PaelsSoldier',
 '化石追踪者': 'FossilStalker',
 '双尾鼠': 'TwoTailedRats',
 '巨斧机器人': 'Axebot'}

# Hand-curated structured overlays: {domain: {key: {en/zh: {name, aliases, detail{...}}}}}
CURATED_EXTRAS: dict[str, dict[str, dict]] = {'powers': {'CRIMSON_MANTLE_POWER': {'en': {'name': 'Crimson Mantle',
                                            'detail': {'power_type': 'Buff',
                                                       'stack_type': 'Counter'}},
                                     'zh': {'name': '猩红披风'}},
            'CRUELTY_POWER': {'en': {'name': 'Cruelty',
                                     'detail': {'power_type': 'Buff', 'stack_type': 'Counter'}},
                              'zh': {'name': '残忍'}},
            'FLEX_POTION_POWER': {'en': {'name': 'Flex Potion Power',
                                         'detail': {'power_type': 'Buff', 'stack_type': 'Counter'}},
                                  'zh': {'name': '屈伸药水之力'}},
            'FLUTTER_POWER': {'en': {'name': 'Flutter',
                                     'detail': {'power_type': 'Buff', 'stack_type': 'Counter'}},
                              'zh': {'name': '振翅'}},
            'INFERNO_POWER': {'en': {'name': 'Inferno',
                                     'detail': {'power_type': 'Buff', 'stack_type': 'Counter'}},
                              'zh': {'name': '狱火'}},
            'JUGGLING_POWER': {'en': {'name': 'Juggling',
                                      'detail': {'power_type': 'Buff', 'stack_type': 'Counter'}},
                               'zh': {'name': '戏法'}},
            'PALE_BLUE_DOT_POWER': {'en': {'name': 'Pale Blue Dot',
                                           'detail': {'power_type': 'Buff',
                                                      'stack_type': 'Counter'}},
                                    'zh': {'name': '苍白蓝点'}},
            'PIERCING_WAIL_POWER': {'en': {'name': 'Piercing Wail',
                                           'detail': {'power_type': 'Debuff',
                                                      'stack_type': 'Counter'}},
                                    'zh': {'name': '穿刺哀嚎'}},
            'REPTILE_TRINKET_POWER': {'en': {'name': 'Reptile Trinket',
                                             'detail': {'power_type': 'Buff',
                                                        'stack_type': 'Counter'}},
                                      'zh': {'name': '爬虫饰品'}},
            'SETUP_STRIKE_POWER': {'en': {'name': 'Setup Strike',
                                          'detail': {'power_type': 'Buff',
                                                     'stack_type': 'Counter'}},
                                   'zh': {'name': '预备打击'}},
            'SLEIGHT_OF_FLESH_POWER': {'en': {'name': 'Sleight of Flesh',
                                              'detail': {'power_type': 'Buff',
                                                         'stack_type': 'Counter'}},
                                       'zh': {'name': '血肉戏法'}},
            'SLOTH_POWER': {'en': {'name': 'Sloth',
                                   'detail': {'power_type': 'Debuff',
                                              'stack_type': 'Counter',
                                              'counter_class': True}},
                            'zh': {'name': '怠惰'}},
            'SPEEDSTER_POWER': {'en': {'name': 'Speedster',
                                       'detail': {'power_type': 'Buff', 'stack_type': 'Counter'}},
                                'zh': {'name': '疾行者'}},
            'SPEED_POTION_POWER': {'en': {'name': 'Speed Potion Power',
                                          'detail': {'power_type': 'Buff',
                                                     'stack_type': 'Counter'}},
                                   'zh': {'name': '速度药水之力'}},
            'SUCK_POWER': {'en': {'name': 'Suck',
                                  'detail': {'power_type': 'Buff', 'stack_type': 'Counter'}},
                           'zh': {'name': '汲取'}},
            'SWIPE_POWER': {'en': {'name': 'Swipe',
                                   'detail': {'power_type': 'Buff', 'stack_type': 'Single'}},
                            'zh': {'name': '夺取'}},
            'BACK_ATTACK_LEFT_POWER': {'en': {'name': 'Back Attack Left',
                                              'detail': {'power_type': 'Buff',
                                                         'stack_type': 'Single'}},
                                       'zh': {'name': '背袭·左'}},
            'BACK_ATTACK_RIGHT_POWER': {'en': {'name': 'Back Attack Right',
                                               'detail': {'power_type': 'Buff',
                                                          'stack_type': 'Single'}},
                                        'zh': {'name': '背袭·右'}},
            'FAN_OF_KNIVES_POWER': {'en': {'name': 'Fan of Knives',
                                           'detail': {'power_type': 'Buff',
                                                      'stack_type': 'Counter'}},
                                    'zh': {'name': '刀扇之力'}},
            'PARRY_POWER': {'en': {'name': 'Parry',
                                   'detail': {'power_type': 'Buff', 'stack_type': 'Counter'}},
                            'zh': {'name': '招架'}},
            'SEEKING_EDGE_POWER': {'en': {'name': 'Seeking Edge',
                                          'detail': {'power_type': 'Buff',
                                                     'stack_type': 'Counter'}},
                                   'zh': {'name': '寻隙锋'}},
            'THE_HUNT_POWER': {'en': {'name': 'The Hunt',
                                      'detail': {'power_type': 'Buff', 'stack_type': 'Counter'}},
                               'zh': {'name': '狩猎'}},
            'THIEVERY_POWER': {'en': {'name': 'Thievery',
                                      'detail': {'power_type': 'Buff', 'stack_type': 'Counter'}},
                               'zh': {'name': '盗窃'}},
            'FORBIDDEN_GRIMOIRE_POWER': {'en': {'name': 'Forbidden Grimoire',
                                                'detail': {'power_type': 'Buff',
                                                           'stack_type': 'Counter'}},
                                         'zh': {'name': '禁忌魔典'}},
            'ROYALTIES_POWER': {'en': {'name': 'Royalties',
                                       'detail': {'power_type': 'Buff', 'stack_type': 'Counter'}},
                                'zh': {'name': '王权'}},
            'THE_SEALED_THRONE_POWER': {'en': {'name': 'The Sealed Throne',
                                               'detail': {'power_type': 'Buff',
                                                          'stack_type': 'Counter'}},
                                        'zh': {'name': '封印王座'}},
            'POSSESS_STRENGTH_POWER': {'en': {'name': 'Possess Strength',
                                              'detail': {'power_type': 'Buff',
                                                         'stack_type': 'Counter'}},
                                       'zh': {'name': '夺力'}},
            'POSSESS_SPEED_POWER': {'en': {'name': 'Possess Speed',
                                           'detail': {'power_type': 'Buff',
                                                      'stack_type': 'Counter'}},
                                    'zh': {'name': '夺迅'}},
            'RAVENOUS_POWER': {'en': {'name': 'Ravenous',
                                      'detail': {'power_type': 'Buff',
                                                 'stack_type': 'Counter',
                                                 'counter_class': True}},
                               'zh': {'name': '贪婪'}},
            'VITAL_SPARK_POWER': {'en': {'name': 'Vital Spark',
                                         'detail': {'power_type': 'Buff',
                                                    'stack_type': 'Counter',
                                                    'counter_class': True}},
                                  'zh': {'name': '生命火花'}}},
 'monsters': {'SEAPUNK': {'en': {'name': 'Seapunk',
                                 'aliases': ['海洋混混', 'Seapunk', 'SeapunkMonster'],
                                 'detail': {'acts': ['Act1'],
                                            'hp': {'base': 45, 'notes': '44-46 base; 47-49 A'},
                                            'is_boss': False,
                                            'passives': [{'power_id': 'RAVENOUS_POWER',
                                                          'amount': None,
                                                          'counter_class': True,
                                                          'description': 'On ally death: self-stun '
                                                                         'devour move + Strength '
                                                                         'gain — see '
                                                                         'RAVENOUS_POWER.'}],
                                            'cycle': ['SEA_KICK_MOVE',
                                                      'SPINNING_KICK_MOVE',
                                                      'BUBBLE_BURP_MOVE'],
                                            'moves': {}}},
                          'zh': {'name': '海洋混混'}},
              'CALCIFIED_CULTIST': {'en': {'name': 'Calcified Cultist',
                                           'aliases': ['钙化邪教徒',
                                                       'CalcifiedCultist',
                                                       'RitualCultist'],
                                           'detail': {'acts': ['Act1', 'Act2'],
                                                      'hp': {'base': 40, 'notes': '38-41 base'},
                                                      'is_boss': False,
                                                      'passives': [{'power_id': 'RITUAL_POWER',
                                                                    'amount': 2,
                                                                    'counter_class': False,
                                                                    'description': 'RITUAL_POWER '
                                                                                   '+2 Strength at '
                                                                                   'end of each of '
                                                                                   'its side turns '
                                                                                   '— see '
                                                                                   'powers.json.'}],
                                                      'cycle': ['INCANTATION_MOVE',
                                                                'DARK_STRIKE_MOVE'],
                                                      'moves': {}}},
                                    'zh': {'name': '钙化邪教徒'}},
              'DampCultist': {'en': {'name': 'Damp Cultist',
                                     'aliases': ['潮湿邪教徒', 'DampCultist', 'RitualCultist'],
                                     'detail': {'acts': ['Act1', 'Act2'],
                                                'hp': {'base': 53, 'notes': '~53 HP class'},
                                                'is_boss': False,
                                                'passives': [{'power_id': 'RITUAL_POWER',
                                                              'amount': None,
                                                              'counter_class': False,
                                                              'description': 'RITUAL_POWER stacks '
                                                                             'vary (e.g. 5) — '
                                                                             'Strength ramps per '
                                                                             'turn start.'}],
                                                'cycle': [],
                                                'moves': {}}},
                              'zh': {'name': '潮湿邪教徒'}},
              'Osty': {'en': {'name': 'Osty',
                              'aliases': ['奥斯提', 'OstyPet'],
                              'detail': {'acts': [],
                                         'hp': {'base': None,
                                                'notes': 'pet summon — HP set by summon source'},
                                         'is_boss': False,
                                         'passives': [{'power_id': 'DIE_FOR_YOU_POWER',
                                                       'amount': None,
                                                       'counter_class': False,
                                                       'description': 'Osty-family death handler — '
                                                                      'combat does not end on '
                                                                      'owner death; pet logic '
                                                                      'revives.'}],
                                         'cycle': [],
                                         'moves': {}}},
                       'zh': {'name': '奥斯提'}},
              'Axebot': {'en': {'name': 'Axebot',
                                'aliases': ['巨斧机器人', 'Axebot'],
                                'detail': {'acts': ['Act2', 'Act3'],
                                           'hp': {'base': None,
                                                  'notes': 'spawn HP not guaranteed full'},
                                           'is_boss': False,
                                           'passives': [{'power_id': 'STOCK_POWER',
                                                         'amount': None,
                                                         'counter_class': True,
                                                         'description': 'STOCK_POWER chain — death '
                                                                        'spawns next robot variant '
                                                                        'with StockAmount-1.'}],
                                           'cycle': [],
                                           'moves': {}}},
                         'zh': {'name': '巨斧机器人'}},
              'GasBomb': {'en': {'name': 'Gas Bomb',
                                 'aliases': ['气态炸弹', 'GasBomb'],
                                 'detail': {'acts': ['Act2'],
                                            'hp': {'base': 7, 'notes': '7 HP minion'},
                                            'is_boss': False,
                                            'passives': [{'power_id': 'MINION_POWER',
                                                          'amount': None,
                                                          'counter_class': False,
                                                          'description': 'Minion mark — death does '
                                                                         'not trigger combat-end '
                                                                         'fatal logic.'}],
                                            'cycle': [],
                                            'moves': {}}},
                          'zh': {'name': '气态炸弹'}},
              'MysteriousKnight': {'en': {'name': 'Mysterious Knight',
                                          'aliases': ['神秘骑士', 'MysteriousKnight'],
                                          'detail': {'acts': ['Act1', 'Act2'],
                                                     'hp': {'base': None,
                                                            'notes': 'event fight — HP not tabled'},
                                                     'is_boss': False,
                                                     'passives': [],
                                                     'cycle': [],
                                                     'moves': {}}},
                                   'zh': {'name': '神秘骑士'}},
              'Assembler': {'en': {'name': 'Assembler',
                                   'aliases': ['组装师', 'Assembler'],
                                   'detail': {'acts': ['Act2', 'Act3'],
                                              'hp': {'base': None, 'notes': 'not tabled'},
                                              'is_boss': False,
                                              'passives': [],
                                              'cycle': [],
                                              'moves': {}}},
                            'zh': {'name': '组装师'}},
              'SneakyGremlin': {'en': {'name': 'Sneaky Gremlin',
                                       'aliases': ['卑鄙地精', 'SneakyGremlin'],
                                       'detail': {'acts': ['Act2'],
                                                  'hp': {'base': 11, 'notes': '11 HP spawn'},
                                                  'is_boss': False,
                                                  'passives': [{'power_id': 'HEIST_POWER',
                                                                'amount': None,
                                                                'counter_class': False,
                                                                'description': 'Escape/reward '
                                                                               'logic marker — see '
                                                                               'powers.json '
                                                                               'HEIST_POWER.'}],
                                                  'cycle': [],
                                                  'moves': {}}},
                                'zh': {'name': '卑鄙地精'}},
              'FatGremlin': {'en': {'name': 'Fat Gremlin',
                                    'aliases': ['胖地精', 'FatGremlin'],
                                    'detail': {'acts': ['Act2'],
                                               'hp': {'base': 17, 'notes': '17 HP spawn'},
                                               'is_boss': False,
                                               'passives': [{'power_id': 'HEIST_POWER',
                                                             'amount': None,
                                                             'counter_class': False,
                                                             'description': 'Escape/reward logic '
                                                                            'marker — see '
                                                                            'powers.json '
                                                                            'HEIST_POWER.'}],
                                               'cycle': [],
                                               'moves': {}}},
                             'zh': {'name': '胖地精'}},
              'PaelsSoldier': {'en': {'name': "Pael's Soldier",
                                      'aliases': ['佩尔的士兵', 'PaelsSoldier'],
                                      'detail': {'acts': ['Act2'],
                                                 'hp': {'base': None, 'notes': 'not tabled'},
                                                 'is_boss': False,
                                                 'passives': [],
                                                 'cycle': [],
                                                 'moves': {}}},
                               'zh': {'name': '佩尔的士兵'}},
              'Larvae': {'en': {'name': 'Larvae',
                                'aliases': ['幼虫', 'Larvae', 'ToughEggHatchling'],
                                'detail': {'acts': ['Act2'],
                                           'hp': {'base': 20, 'notes': '19-21 HP'},
                                           'is_boss': False,
                                           'passives': [{'power_id': 'MINION_POWER',
                                                         'amount': None,
                                                         'counter_class': False,
                                                         'description': 'Minion mark — death does '
                                                                        'not end combat.'}],
                                           'cycle': ['NIBBLE_MOVE'],
                                           'moves': {}}},
                         'zh': {'name': '幼虫'}},
              'CoralCluster': {'en': {'name': 'Coral Cluster',
                                      'aliases': ['鬼祟珊瑚群',
                                                  'Coral Cluster',
                                                  'SkulkingColony',
                                                  'Skulking Colony',
                                                  'CoralCluster'],
                                      'detail': {'acts': ['Act1'],
                                                 'hp': {'base': 75, 'notes': '75 HP elite'},
                                                 'is_boss': True,
                                                 'passives': [{'power_id': 'HARDENED_SHELL_POWER',
                                                               'amount': 20,
                                                               'counter_class': True,
                                                               'description': 'HP loss per turn '
                                                                              'capped at Amount '
                                                                              'minus damage '
                                                                              'already taken this '
                                                                              'turn — pace to '
                                                                              'exactly 20/turn.'}],
                                                 'cycle': ['SMASH_MOVE',
                                                           'ZOOM_MOVE',
                                                           'INERTIA_MOVE',
                                                           'PIERCING_STABS_MOVE'],
                                                 'moves': {}}},
                               'zh': {'name': '鬼祟珊瑚群'}},
              'SkulkingColony': {'en': {'name': 'Skulking Colony',
                                        'aliases': ['Skulking Colony',
                                                    'CoralCluster',
                                                    'Coral Cluster',
                                                    '鬼祟珊瑚群'],
                                        'detail': {'acts': ['Act1'],
                                                   'hp': {'base': 75, 'notes': '75 HP elite'},
                                                   'is_boss': True,
                                                   'passives': [{'power_id': 'HARDENED_SHELL_POWER',
                                                                 'amount': 20,
                                                                 'counter_class': True,
                                                                 'description': 'HP loss per turn '
                                                                                'capped at Amount '
                                                                                'minus damage '
                                                                                'already taken '
                                                                                'this turn.'}],
                                                   'cycle': [],
                                                   'moves': {}}},
                                 'zh': {'name': '鬼祟珊瑚群'}},
              'BattleFriendV2': {'en': {'name': 'Battle Friend V2.0',
                                        'aliases': ['战斗好伙伴V2.0', 'BattleFriendV2'],
                                        'detail': {'acts': ['Act3'],
                                                   'hp': {'base': 150,
                                                          'notes': '150 HP flat single-player'},
                                                   'is_boss': False,
                                                   'passives': [{'power_id': 'BATTLEWORN_DUMMY_TIME_LIMIT_POWER',
                                                                 'amount': 3,
                                                                 'counter_class': True,
                                                                 'description': 'Decrees at end of '
                                                                                'dummy side turns; '
                                                                                'at 1 dummy '
                                                                                'escapes — no '
                                                                                'reward.'}],
                                                   'cycle': ['NOTHING_MOVE'],
                                                   'moves': {}}},
                                 'zh': {'name': '战斗好伙伴V2'}},
              'BattleFriendV3': {'en': {'name': 'Battle Friend V3.0',
                                        'aliases': ['战斗好伙伴V3.0', 'BattleFriendV3'],
                                        'detail': {'acts': ['Act3'],
                                                   'hp': {'base': 300,
                                                          'notes': '300 HP flat single-player'},
                                                   'is_boss': False,
                                                   'passives': [{'power_id': 'BATTLEWORN_DUMMY_TIME_LIMIT_POWER',
                                                                 'amount': 3,
                                                                 'counter_class': True,
                                                                 'description': 'Decrees at end of '
                                                                                'dummy side turns; '
                                                                                'at 1 dummy '
                                                                                'escapes — no '
                                                                                'reward.'}],
                                                   'cycle': ['NOTHING_MOVE'],
                                                   'moves': {}}},
                                 'zh': {'name': '战斗好伙伴V3.0'}},
              'IRONCLAD': {'en': {'name': 'Ironclad (player)',
                                  'aliases': ['铁甲战士', 'CHARACTER.IRONCLAD'],
                                  'detail': {'acts': [],
                                             'hp': {'base': 80, 'notes': 'player character'},
                                             'is_boss': False,
                                             'passives': [],
                                             'cycle': [],
                                             'moves': {}}},
                           'zh': {'name': '铁甲战士（玩家）'}},
              'SILENT': {'en': {'name': 'Silent (player)',
                                'aliases': ['静默猎手', 'CHARACTER.SILENT'],
                                'detail': {'acts': [],
                                           'hp': {'base': 70, 'notes': 'player character'},
                                           'is_boss': False,
                                           'passives': [],
                                           'cycle': [],
                                           'moves': {}}},
                         'zh': {'name': '静默猎手（玩家）'}},
              'REGENT': {'en': {'name': 'Regent (player)',
                                'aliases': ['储君', 'CHARACTER.REGENT'],
                                'detail': {'acts': [],
                                           'hp': {'base': 75, 'notes': 'player character'},
                                           'is_boss': False,
                                           'passives': [],
                                           'cycle': [],
                                           'moves': {}}},
                         'zh': {'name': '储君（玩家）'}},
              'NECROBINDER': {'en': {'name': 'Necrobinder (player)',
                                     'aliases': ['亡灵契约师', 'CHARACTER.NECROBINDER'],
                                     'detail': {'acts': [],
                                                'hp': {'base': 66, 'notes': 'player character'},
                                                'is_boss': False,
                                                'passives': [],
                                                'cycle': [],
                                                'moves': {}}},
                              'zh': {'name': '亡灵契约师（玩家）'}},
              'DEFECT': {'en': {'name': 'Defect (player)',
                                'aliases': ['故障机器人', 'CHARACTER.DEFECT'],
                                'detail': {'acts': [],
                                           'hp': {'base': 75, 'notes': 'player character'},
                                           'is_boss': False,
                                           'passives': [],
                                           'cycle': [],
                                           'moves': {}}},
                         'zh': {'name': '故障机器人（玩家）'}}},
 'events': {'NONUPEIPE': {'en': {'name': 'Nonupeipe'}, 'zh': {'name': '诺努佩佩'}}}}

# Curated move tables: {monster_key: {move_key: (move_id, name, intent, base_damage, asc, hits)}}
CURATED_MOVES = {'SEAPUNK': {'SEA_KICK_MOVE': ('SEA_KICK_MOVE',
                               'Sea Kick',
                               {'class': 'SingleAttackIntent',
                                'type': 'Attack',
                                'base_damage': 11,
                                'hits': 1,
                                'base_damage_ascension': 13},
                               11,
                               13,
                               1),
             'SPINNING_KICK_MOVE': ('SPINNING_KICK_MOVE',
                                    'Spinning Kick',
                                    {'class': 'MultiAttackIntent',
                                     'type': 'Attack',
                                     'base_damage': 2,
                                     'hits': 4},
                                    2,
                                    None,
                                    4),
             'BUBBLE_BURP_MOVE': ('BUBBLE_BURP_MOVE', 'Bubble Burp', None, None, None, None),
             'GLOMP_MOVE': ('GLOMP_MOVE',
                            'Glomp',
                            {'class': 'SingleAttackIntent',
                             'type': 'Attack',
                             'base_damage': 8,
                             'hits': 1},
                            8,
                            None,
                            1),
             'WHIP_SLAP_MOVE': ('WHIP_SLAP_MOVE',
                                'Whip Slap',
                                {'class': 'MultiAttackIntent',
                                 'type': 'Attack',
                                 'base_damage': 3,
                                 'hits': 2},
                                3,
                                None,
                                2),
             'GOOP_MOVE': ('GOOP_MOVE',
                           'Goop',
                           {'class': 'DebuffIntent', 'type': 'Debuff'},
                           None,
                           None,
                           None)},
 'CALCIFIED_CULTIST': {'INCANTATION_MOVE': ('INCANTATION_MOVE',
                                            'Incantation',
                                            {'class': 'BuffIntent', 'type': 'Buff'},
                                            None,
                                            None,
                                            None),
                       'DARK_STRIKE_MOVE': ('DARK_STRIKE_MOVE',
                                            'Dark Strike',
                                            {'class': 'SingleAttackIntent',
                                             'type': 'Attack',
                                             'base_damage': 9,
                                             'hits': 1,
                                             'base_damage_ascension': 11},
                                            9,
                                            11,
                                            1)}}
